const ICON_TYPES = [
  '1-solid',
  '1',
  '2-solid',
  '2',
  '3-solid',
  '3',
  '4',
  'arrow-down',
  'arrow-left-solid',
  'arrow-left',
  'arrow-right-solid',
  'arrow-right',
  'arrow-up',
  'bolt',
  'card-bolt',
  'charger-chademo',
  'charger-css-ac',
  'charger-css',
  'charger-css1',
  'charger-gbt',
  'charger-mcs',
  'charger-nacs',
  'charger-type-1-j1772',
  'credit-card',
  'danger',
  'device',
  'error',
  'globe',
  'hourglass',
  'house',
  'l',
  'loader',
  'minus',
  'padlock',
  'plug',
  'price',
  'question',
  'r',
  'reciept',
  'telephone',
  'tick',
  'timer',
  'warning',
] as const

type IconType = (typeof ICON_TYPES)[number]
export type { IconType }

export { ICON_TYPES }
